<?php

/**
 * Set dynamic links according to main group (centralbibliotek).
 *
 * The link will be changed in hook_translated_menu_link_alter().
 * We need to edit and save the link for the option alter to work.
 *
 * Implements hook_menu_link_alter().
 */
function cbib_menu_menu_link_alter(&$link) {
  if ($link['link_path'] == variable_get('site_frontpage') || $link['link_path'] == '<front>') {
    $link['options']['alter'] = TRUE;
  }
  elseif (in_array($link['link_path'], array('events', 'groups', 'news'))) {
    $link['options']['alter'] = TRUE;
  }
}

/**
 * Change links according to main group (centralbibliotek).
 *
 * Implements hook_translated_menu_link_alter().
 */
function cbib_menu_translated_menu_link_alter(&$item, $map) {
  $cbib_menu = &drupal_static('cbib_menu', array());

  if (!empty($cbib_menu['nid'])) {
    if ($item['href'] == variable_get('site_frontpage') || $item['href'] == '<front>') {
      $item['href'] = "node/{$cbib_menu['nid']}";
      $item['title'] = $cbib_menu['title'];
    }
    elseif (in_array($item['href'], array('events', 'groups', 'news'))) {
      $item['href'] = "node/{$cbib_menu['nid']}/{$item['href']}";
    }
  }
  // Set homepage link to front without alias.
  if ($item['href'] == variable_get('site_frontpage') || $item['href'] == '<front>') {
    $item['href'] = '';
    $item['title'] = t('Home');
  }

  // Add active trail.
  $active_trail = end(menu_get_active_trail());
  if (!empty($active_trail['href']) && $active_trail['href'] == $item['href']) {
    $item['in_active_trail'] = TRUE;
  }
}

/**
 * Logic to handle which central library that has been chosen last.
 *
 * Implements hook_init().
 */
function cbib_menu_init() {
  $cbib_menu = &drupal_static('cbib_menu', array());

  if (drupal_is_front_page()) {
      $cbib_menu['nid'] = FALSE;
  }
  elseif (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    if ($node->type == 'centralbibliotek') {
      $cbib_menu['nid'] = $node->nid;
      $cbib_menu['title'] = $node->title;
    }
  }
}

