<?php

include_once 'includes/cbib_oc_comments_new_api.inc';
include_once 'includes/cbib_oc_comments_new_callbacks.inc';
//set up menu routes
function cbib_oc_comments_new_menu() {
  $items = array();

  $items['cbib/oc/comments/ajax/add'] = array(
    'page callback' => 'cbib_oc_comments_new_comment_add',
    'delivery callback' => 'ajax_deliver',
    'access arguments' => array('access content'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );
  $items['cbib/oc/comments/ajax/remove/%'] = array(
    'page callback' => 'cbib_oc_comments_new_post_remove',
    'delivery callback' => 'ajax_deliver',
    'page arguments' => array(5),
    'access arguments' => array('access content'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );
  $items['cbib/oc/comments/ajax/remove/comment/%'] = array(
    'page callback' => 'cbib_oc_comments_new_comment_remove',
    'delivery callback' => 'ajax_deliver',
    'page arguments' => array(6),
    'access arguments' => array('access content'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );
  $items['cbib/oc/comments/ajax/get/%'] = array(
    'page callback' => 'cbib_oc_comments_new_comment_get',
    'delivery callback' => 'ajax_deliver',
    'page arguments' => array(5),
    'access arguments' => array('access content'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );
   $items['cbib/oc/comments/ajax/update/%'] = array(
    'page callback' => 'cbib_oc_comments_post_update',
    'delivery callback' => 'ajax_deliver',
    'page arguments' => array(5),
    'access arguments' => array('access content'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );
      $items['cbib/oc/comments/ajax/update/comment/%'] = array(
    'page callback' => 'cbib_oc_comments_comment_update',
    'delivery callback' => 'ajax_deliver',
    'page arguments' => array(6),
    'access arguments' => array('access content'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );
  $items['cbib/oc/comments/ajax/getform/%'] = array(
    'page callback' => 'cbib_oc_comments_render_comment_form',
    'delivery callback' => 'drupal_json_output',
    'page arguments' => array(5),
    'access arguments' => array('access content'),
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


//Alter the comment form
function cbib_oc_comments_new_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == "commons_bw_partial_node_form__post")
    {
        $form['actions']['submit']['#ajax'] = array(
            'callback' => 'cbib_oc_comments_new_post_add',
            'effect' => 'fade',
        );
        unset($form['#submit']);
    }
}
//Add buttons to the posts.
function cbib_oc_comments_new_node_view_alter(&$build)
{
    global $user;
    if($build['#node']->type == "post")
    {
        
        drupal_add_library('system', 'drupal.ajax');
        drupal_add_library('system', 'jquery.form');
        drupal_add_js(drupal_get_path('module', 'cbib_oc_comments_new') . '/js/cbib_oc_comments_new.js');
        drupal_add_css(drupal_get_path('module', 'cbib_oc_comments_new') . '/css/cbib_oc_comments_new.css');
        if(isset($build['comments']['comments']))
        {
                $build['comments']['#prefix'] = '<div class="cbib-oc-comment-ajax-wrap-'.$build['#node']->nid.'"><div>';
                $build['comments']['#suffix'] = '</div></div>';
                cbib_oc_comments_add_wrappers($build['comments']['comments']);
                unset($build['comments']['comment_form']);
        }
        $html_reply = '<div class="oc-comments-new-reply-btn"><span class=""><i class="fa fa-reply"></i>Svar</span></div>';
        $html_edit = '<div class="oc-comments-new-edit-btn"><span class=""><i class="fa fa-pencil" aria-hidden="true"></i>Rediger</span></div>';
        $html_slet = '<div class="oc-comments-new-delete-btn"><span class=""><i class="fa fa-trash" aria-hidden="true"></i>Slet</span></div>';
        if(!user_is_anonymous())
        {
            $build['links']['svar'] = array('#theme'=>'html_tag','#links'=> array('oc-comments-new-reply-wrap' => array('title' => $html_reply,'html' => true)),'#attributes' => array('class' => array('links','inline')));
            if(node_access("update",$build['#node']))
            {
                $build['links']['ret'] = array('#theme'=>'html_tag','#links'=> array('oc-comments-new-edit-wrap' => array('title' => $html_edit,'html' => true)),'#attributes' => array('class' => array('links','inline')));
                $build['links']['slet'] = array('#theme'=>'html_tag','#links'=> array('oc-comments-new-delete-wrap' => array('title' => $html_slet,'html' => true)),'#attributes' => array('class' => array('links','inline')));
            }
            
        }
        $build['cbib_oc_comments_new'][] = array('#markup' => "<input type='hidden' id='cbib-oc-comments-new-nid' value='".$build['#node']->nid."' />");
        $build['cbib_new_comment_block'] = array('#markup'=>"<div class='oc-new-comment-block-wrap-".$build['#node']->nid."'></div>");
        //$build['links']['svar'] = array('#markup'=>$html);
        //$build['links']['svar'] = array('#markup' => l(t('Link text'),'node'));
    } 
    
}
function  cbib_oc_comments_new_comment_view_alter(&$build, $view_mode) {
    $build['links']['comment']['#links']['comment-reply']['title'] = '<div class="action-item-small action-item-inline"><span class=""><i class="fa fa-reply"></i>Svar</span></div>';
    $build['links']['comment']['#links']['comment-reply']['html'] = 'true';
    
    $build['links']['comment']['#links']['comment-edit']['title'] = '<div class="action-item-small action-item-inline"><span class=""><i class="fa fa-pencil"></i>Edit</span></div>';
    $build['links']['comment']['#links']['comment-edit']['html'] = 'true';
}