<?php

/**
 * @file
 * Centralbibliotek.dk event stuff.
 */

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function cbib_events_ctools_plugin_directory($module, $plugin) {
  if (($module == 'ctools' || $module == 'panels') && ($plugin == 'content_types')) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements ctools_plugin_api().
 */
function cbib_events_ctools_plugin_api() {
  $args = func_get_args();
  $module = array_shift($args);
  $api = array_shift($args);
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function cbib_events_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($router_item['path'] == 'node/%/registrations' || $router_item['tab_parent'] == 'node/%/registrations') {
    $data['tabs'][1]['output'][] = array(
      '#theme' => 'menu_local_task',
      '#link' => array(
        'title' => t('Download registrants'),
        'href' => 'node/' . $router_item['original_map'][1] . '/registrations/deltagere.csv',
        'localized_options' => array(
          'attributes' => array(
            'title' => t('Download'),
          ),
        ),
      ),
    );
  }
}
