<?php
/**
 * @file
 * Code for the Cbib Events feature.
 */

include_once 'cbib_events.features.inc';

/**
 * @file
 * Centralbibliotek.dk event stuff.
 */

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function cbib_events_ctools_plugin_directory($module, $plugin) {
  if (($module == 'ctools' || $module == 'panels') && ($plugin == 'content_types')) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function cbib_events_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($router_item['path'] == 'node/%/registrations' || $router_item['tab_parent'] == 'node/%/registrations') {
    $data['tabs'][1]['output'][] = array(
      '#theme' => 'menu_local_task',
      '#link' => array(
        'title' => t('Download registrants'),
        'href' => 'node/' . $router_item['original_map'][1] . '/registrations/deltagere.csv',
        'localized_options' => array(
          'attributes' => array(
            'title' => t('Download'),
          ),
        ),
      ),
    );
  }
}


/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function cbib_events_form_event_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_registration_date']['und'][0]['#title'] = 'Tilmelding åbner';
  $form['#attached']['css'] = array(
    drupal_get_path('module', 'cbib_events') . '/css/node-edit.css',
  );
}
