<?php

/**
 * This is example code for a Drupal 6 to Drupal 7 migration. This won't actually
 * work without defining the referenced vocabularies, content types, and fields
 * on each side.
 */

/**
 * Implements hook_flush_caches().
 */
function cbib_migrate_flush_caches() {
  cbib_migrate_register_migrations();
}

/**
 * Register all D6->D7 migrations.
 */
function cbib_migrate_register_migrations() {
  // Define how we are getting the data for the migration. Legacy connector
  // from settings.php and 6 as major Drupal version.
  $common_arguments = array(
    'source_connection' => 'legacy',
    'source_version' => 6,
  );

  // Get migrations for users and their profile nodes.
  $migrations  = cbib_migrate_register_user_migration();

  // Get migrations for images (Billedefil/media -> Billede).
  $migrations += cbib_migrate_register_image_migration();

  // Get migrations for central libraries (Centralbibliotek/library -> Centralbibliotek/centralbibliotek).
  $migrations += cbib_migrate_register_central_library_migration();

  // Get migrations for groups (Gruppe/group -> Gruppe/group).
  $migrations += cbib_migrate_register_group_migration();

  // Get migrations for events (Arrangement/event -> Begivenhed/event).
  $migrations += cbib_migrate_register_event_migration();

  // Get migrations for documents (Gruppefil/group_file -> Dokument/document).
  $migrations += cbib_migrate_register_document_migration();

  // Get migrations for posts (Gruppenyhed/group_news -> Indlæg/post).
  $migrations += cbib_migrate_register_post_migration();

  // Get migrations for news items (Nyhed/newsitem -> Nyhed/news).
  $migrations += cbib_migrate_register_news_item_migration();

  // Get migrations for pages (Tekstside/textpage -> Site/page).
  $migrations += cbib_migrate_register_page_migration();

  // Register all the migrations.
  cbib_migrate_register_migrations($common_arguments, $migrations);
}

/**
 * Implements hook_migrate_api().
 */
function cbib_migrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Get migrations for users and their profile nodes.
 *
 * @return Array containing the arguments of the migration ('arguments' array key)
 *   and the class that handles the migration ('class' array key).
 */
function cbib_migrate_register_user_migration() {
  $migrations = array();

  $user_migration = array(
    'description' => t('Migration of users from Centralbibliotek.dk'),
    'machine_name' => 'user',
  );

  $migrations[] = array(
    'arguments' => $user_migration,
    'class' => 'CbibUserMigration',
  );

  return $migrations;
}

/**
 * Get migrations for images (Billedefil/media -> Billede).
 *
 * @see cbib_migrate_register_user_migration().
 */
function cbib_migrate_register_image_migration() {
  $migrations = array();

  return $migrations;
}

/**
 * Get migrations for central libraries (Centralbibliotek/library -> Centralbibliotek/centralbibliotek).
 *
 * @see cbib_migrate_register_user_migration().
 */
function cbib_migrate_register_central_library_migration() {
  $migrations = array();

  $central_library_migration = array(
    'description' => t('Migration of central library nodes from Centralbibliotek.dk'),
    'machine_name' => 'central_library',
    'source_type' => 'library',
    'destination_type' => 'centralbibliotek',
    'user_migration' => 'user',
  );

  $migrations[] = array(
    'arguments' => $central_library_migration,
    'class' => 'CentralLibraryMigration',
  );

  return $migrations;
}

/**
 * Get migrations for groups (Gruppe/group -> Gruppe/group).
 *
 * @see cbib_migrate_register_user_migration().
 */
function cbib_migrate_register_group_migration() {
  $migrations = array();

  return $migrations;
}

/**
 * Get migrations for events (Arrangement/event -> Begivenhed/event).
 *
 * @see cbib_migrate_register_user_migration().
 */
function cbib_migrate_register_event_migration() {
  $migrations = array();

  return $migrations;
}

/**
 * Get migrations for documents (Gruppefil/group_file -> Dokument/document).
 *
 * @see cbib_migrate_register_user_migration().
 */
function cbib_migrate_register_document_migration() {
  $migrations = array();

  return $migrations;
}

/**
 * Get migrations for posts (Gruppenyhed/group_news -> Indlæg/post).
 *
 * @see cbib_migrate_register_user_migration().
 */
function cbib_migrate_register_post_migration() {
  $migrations = array();

  return $migrations;
}

/**
 * Get migrations for news items (Nyhed/newsitem -> Nyhed/news).
 *
 * @see cbib_migrate_register_user_migration().
 */
function cbib_migrate_register_news_item_migration() {
  $migrations = array();

  return $migrations;
}

/**
 * Get migrations for pages (Tekstside/textpage -> Site/page).
 *
 * @see cbib_migrate_register_user_migration().
 */
function cbib_migrate_register_page_migration() {

  $migrations = array();

  return $migrations;
}
