<?php

/**
 * @file
 * Install, update and uninstall functions for the cbib module.
 */

/**
 * Implements hook_schema_alter().
 *
 * Set Danish collation on title fields.
 */
function cbib_schema_alter(&$schema) {
  $schema['field_data_title_field']['collation'] = 'utf8_danish_ci';
}

/**
 * Fix collation of {field_data_title_field}.
 */
function cbib_update_7101(&$sandbox) {
  module_enable(array('collation_fixer'));
  collation_fixer_fix_collation('field_data_title_field');
}
