<?php
/**
 * @file
 * cbib_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function cbib_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-7WTgHb2zdhyHCsRZtsXnU3eogApOW342'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7WTgHb2zdhyHCsRZtsXnU3eogApOW342',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'cb',
        'weight' => -26,
      ),
    ),
    'title' => 'Afholdelsessted',
    'visibility' => 0,
  );

  $export['facetapi-BFZ195FyIkWBzXNTaq3jevkbxSWXJpMb'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BFZ195FyIkWBzXNTaq3jevkbxSWXJpMb',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cb',
        'weight' => -23,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-JwI0KJa49LTyb0b8boxg0WXl9IJP1Sq5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'JwI0KJa49LTyb0b8boxg0WXl9IJP1Sq5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'cb',
        'weight' => -27,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-NjamMRlUSiv6J1uYtpZ6KmDlsOuSofFX'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'NjamMRlUSiv6J1uYtpZ6KmDlsOuSofFX',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cb',
        'weight' => -24,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-XHLAnjHeOAp0axOkfh8bhAJafcP3GwNf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'XHLAnjHeOAp0axOkfh8bhAJafcP3GwNf',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'cb',
        'weight' => -29,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-cqaFaNfbmSLAYERqskR8OE6icuXJcFgZ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cqaFaNfbmSLAYERqskR8OE6icuXJcFgZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'cb',
        'weight' => -23,
      ),
    ),
    'title' => 'Dato',
    'visibility' => 0,
  );

  $export['facetapi-gw7MYX93nFUXP6kzts1Eay6QpCVVSaOt'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'gw7MYX93nFUXP6kzts1Eay6QpCVVSaOt',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cb',
        'weight' => -22,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-k9aJWJ4JDEw6hhSBq3IrGlonhn6ry6sY'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'k9aJWJ4JDEw6hhSBq3IrGlonhn6ry6sY',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cb',
        'weight' => -24,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-lyyyTQZmDqHX6b30Dx4mzfY6gEOR5Y0j'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'lyyyTQZmDqHX6b30Dx4mzfY6gEOR5Y0j',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cb',
        'weight' => -25,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-nStXbzwvJkrh5OGgbz5zOHidQX0A1Ynt'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nStXbzwvJkrh5OGgbz5zOHidQX0A1Ynt',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'cb',
        'weight' => -25,
      ),
    ),
    'title' => 'Pris',
    'visibility' => 0,
  );

  $export['facetapi-pRP605Up4z9FXEyXfaRUJXanTZ71ktX4'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pRP605Up4z9FXEyXfaRUJXanTZ71ktX4',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'cb',
        'weight' => -28,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-rJ41iuaZ0tI1G1AP2gFnVQy6bjKDQf2J'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'rJ41iuaZ0tI1G1AP2gFnVQy6bjKDQf2J',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'cb',
        'weight' => -27,
      ),
    ),
    'title' => 'Type',
    'visibility' => 0,
  );

  $export['facetapi-vz7fXD33KaD1bx0f8BW4chLaEYtyDB10'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'vz7fXD33KaD1bx0f8BW4chLaEYtyDB10',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'cb',
        'weight' => -30,
      ),
    ),
    'title' => 'Indholdstype',
    'visibility' => 0,
  );

  $export['facetapi-yz9XmKQdPPifJdPJudYeRDV3PpGykc25'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'yz9XmKQdPPifJdPJudYeRDV3PpGykc25',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'cb' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cb',
        'weight' => -26,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
