<?php
include_once "cbib_oc_hooks.admin.inc";

/**
 * Implements hook_init().
 */
function cbib_oc_hooks_init() {
  if (!drupal_is_cli()) {
    // Path of your page with search results.
     
      $path_parts = explode('?', request_uri());
      /* @var $path_parts type */
      if (strpos($path_parts[1], 'field_date_value=past') !== false ) {

      }else {
            // Name of your searcher.
      // In this case "search_api" is service
      // and "solr_index" is machine name of the index.
      $part = explode('/', $path_parts[0]);
      if($part[2] == 'grupper') {
        $searcher = 'search_api@group_index';
      }else {
        $searcher = 'search_api@arrangement_index';
      }
      $adapter = facetapi_adapter_load($searcher);
      $url_processor = $adapter->getUrlProcessor();

      // Check if the filter is already active.
        if ($part[3] != 'events') {
        $filter = "field_date%3Avalue:future";
        }

      $active_items = $adapter->getAllActiveItems();
      $filter_key = $url_processor->getFilterKey();
      $params = $url_processor->fetchParams();
      if (!isset($active_items[$filter])) {

        // If not, get and tamper with your parameters here.
        
        $params[$filter_key][] = $filter;
        
      }
      /*
       * Have we selected cb ? 
       * And Is the og_reg_filter_active ?
       */
      $selected_cbib = $_SESSION['cbib_centralbibliotek'];
      if($selected_cbib != false && !isset($_GET['og_group_ref']))
      {
          drupal_add_js(array('oc_cbib' => array('centralbib' => $selected_cbib)), 'setting');
          $is_active_selection = false;
          foreach($active_items as $key => $value)
          {
              if($value['field alias'] == "og_group_ref" && $value['value'] != $selected_cbib)
              {
                  $is_active_selection = true;
              }
          }
          if(!$is_active_selection)
          {
              // If not, get and tamper with your parameters here.
             
              $params[$filter_key][] = "og_group_ref:" . $selected_cbib;
              //$adapter->setParams($params, $filter_key);
          }
      }
      $selected_cbib = $_SESSION['cbib_centralbibliotek'];
      if($selected_cbib != false && !isset($_GET['node_og_group_ref']))
      {
          drupal_add_js(array('oc_cbib' => array('centralbib' => $selected_cbib)), 'setting');
          $is_active_selection = false;
          foreach($active_items as $key => $value)
          {
              if($value['field alias'] == "node_og_group_ref" && $value['value'] != $selected_cbib)
              {
                  $is_active_selection = true;
              }
          }
          if(!$is_active_selection)
          {
              // If not, get and tamper with your parameters here.
             
              $params[$filter_key][] = "node_og_group_ref:" . $selected_cbib;
              //$adapter->setParams($params, $filter_key);
          }
      }
      $adapter->setParams($params, $filter_key);
    }
}
}
/*
 * Register any additonal routes required by the module.
 */
function  cbib_oc_hooks_menu() {
  $items = array();
  $items['admin/settings/cbib_oc_hooks'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Cbib OC_Hooks config',
    'description' => 'Config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cbib_oc_hooks_admin'),
    'access arguments' => array('administer cbib_hooks'),
    'access callback' => TRUE,
   );

   $items['admin/settings/cbib_oc_hooks/js/summary'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'js_summary',
    'description' => 'creates summary of text recived and returns',
    'page callback' => 'cbib_oc_hooks_js_create_summary',
    'access arguments' => array('administer cbib_hooks'),
    'access callback' => TRUE,
   );

  $items['oc/user/autocomplete'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'autocomplete with names + emails.',
    'description' => 'modified user autocomplete',
    'page callback' => 'cbib_oc_hooks_user_autocomplete',
    'access callback' => 'user_access',
    'access arguments' => array('access user profiles'),
   );

    $items['group/%/%/admin/oc/resend'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Resend group notification.',
    'description' => 'send group notification',
    'page arguments' => array(1, 2),
    'page callback' => 'cbib_oc_hooks_og_resend_notifcation',
    'access callback' => 'og_ui_user_access_group',
    'access arguments' => array('add user', 1, 2),
   );

    $items['admin/rebuild/nodes/last/posts'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'rebuild',
    'description' => 'rebuild',
    'page callback' => 'update_all_groups_with_comments',
    'access callback' => 'user_access',
    'access arguments' => array('access user profiles'),

   );
   $items['flag/flag/follow/all/library'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'test',
    'description' => 'test',
    'page callback' => 'user_follow_all_library_licenes',
    'access callback' => 'user_access',
    'access arguments' => array('access user profiles'),
   );
   
  return $items;
}

function cbib_oc_hooks_menu_alter(&$items) {
         // entity local tasks
foreach (registration_get_registration_instances() as $instance) {
  $type = $instance['entity_type'];
  if (!in_array($type, array('registration', 'registration_type'))) {
      $items[$type . '/%entity_object/registrations']['access callback'] = 'cbib_oc_hooks_registration_administer_registrations_access';
      $items[$type . '/%entity_object/registrations/list']['access callback'] = 'cbib_oc_hooks_registration_administer_registrations_access';
      $items[$type . '/%entity_object/registrations/settings']['access callback'] = 'cbib_oc_hooks_registration_administer_registrations_access';
      $items[$type . '/%entity_object/registrations/broadcast']['access callback'] = 'cbib_oc_hooks_registration_administer_registrations_access';
    }
  }
 return $items;
}

function cbib_oc_hooks_registration_administer_registrations_access ($entity_type, $entity) {

  if (og_user_access('node', $entity->nid, 'administrator members')) {
    return TRUE;
  }
  $registration_type = registration_get_entity_registration_type($entity_type, $entity);
   if ($registration_type) {
  if (user_access("administer $registration_type registration")) {
    return TRUE;
  }
  elseif (user_access("administer own $registration_type registration") && entity_access('update', $entity_type, $entity)) {
    return TRUE;
    }
  }
  return FALSE;
}

function cbib_oc_hooks_registration_access($op, Registration $registration = NULL, $account = NULL) {

   if (og_user_access('node', $registration->entity_id, 'administrator members')) {
      return TRUE;
   }

}


/**
 * Implements hook_permission().
 */
function cbib_oc_hooks_permission() {
  return array(
    'administer cbib_hooks' => array(
      'title' => t('Administrer digitalpost'),
      'description' => t('Giver adgang til configuere digitalpost'),
    )
  );
}

/**
 * By enabling this filter, items of this facet can be rewritten prior to rendering by implementing the hook: 
 */
function cbib_oc_hooks_facet_items_alter(&$build, &$settings) {
  if ($settings->facet == "field_date:value") {
    foreach($build as $key => $item) {
      unset($build[$key]['#count']);
    }
  }

  if ($settings->facet == "field_address:locality") {
  $locations = cbib_oc_hooks_get_all_event_locations();
  $loca = array();
  foreach($locations as $id => $loc) {
    if ($build[$id]["#markup"] == $loc) {
      $loca[$id] = $build[$id];  
      }
    if ($loc == '') {
      unset($loca[$id]);
    }

  }

      $build = $loca;
  }
  if ($settings->facet == "og_group_ref" || $settings->facet == "node:og_group_ref") {
      
      //$CentralLibraries = null;
      $CentralLibraries_nids = null;
      $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'node')
          ->entityCondition('bundle', 'centralbibliotek')
          ->propertyCondition('status', NODE_PUBLISHED)
          // Run the query as user 1.
          ->addMetaData('account', user_load(1));

        $result = $query->execute();
        if (isset($result['node'])) {
          $CentralLibraries_nids = array_keys($result['node']);
          //$CentralLibraries = entity_load('node', $CentralLibraries_nids);
        } 
      foreach($build as $key => $item) {
        if(!in_array($key, $CentralLibraries_nids))
        {
            //remove non cbib nodes from tilknytning result.
            unset($build[$key]);
        }
      }
    }
}
/*
* Alter various forms.
 */
function cbib_oc_hooks_form_alter(&$form, &$form_state, $form_id)
{
    if($form_id == "user_register_form")
    {
        hide($form['actions']['submit']);
        $form['actions']['submit2']['#value'] = t("Send");
        $form['actions']['submit2']['#type'] = "submit";
    }
    if($form_id == "user_login")
    {
        //Added ability to referer to last page before login.
        $referer = $_SERVER['HTTP_REFERER'];
        $parsed = parse_url($referer, PHP_URL_PATH);
        if ($parsed != '/user/login') {
        $_SESSION['ref'] = $parsed;
        }
        $form['#submit'][] = 'cbib_oc_hooks_user_login_submit_handler';
    }
    if($form_id == "event_node_form")
    {
        //drupal_add_js(drupal_get_path('module', 'cbib_oc_hooks') .'/js/end-date.js',array('weight' => 999));
        /*
         * JS to create live preview of summary.
         */
        drupal_add_js(array('cbib_oc_hooks' => array('summary_length' => variable_get('teaser_length', 600))), 'setting');
        drupal_add_js(drupal_get_path('module', 'cbib_oc_hooks') .'/js/oc_summary_preview.js');

        array_unshift($form['#validate'], "validate_online_adresses_fix");
    }
    if($form_id == "og_ui_add_users" && isset($form['og_user']['name']['#autocomplete_path']))
    {
        $form['og_user']['name']['#autocomplete_path'] = 'oc/user/autocomplete';
    }
    if($form_id == "news_node_form" || $form_id == "event_node_form" || $form_id == "library_node_form"
        || $form_id == "centralbibliotek_node_form" || $form_id == "group_node_form" || $form_id == "license_node_form"
        || $form_id == "licenses_node_form" || $form_id == "page_node_form" || $form_id == "document_node_form"
        || $form_id == "post_node_form")
    {
      // Add checkbox option
       $form['options']['gensend_notifcation'] = array(
        '#type' => 'checkbox',
        '#title' => t('Genudsend notifcation'),
        '#default_value' => 0,
      );
    }
    if($form_id == "group_node_form")
    {
        hide($form['field_last_comment_date']);
    }
}
function validate_online_adresses_fix(&$form,&$form_state)
{
}
/**
 * Implements hook_form_BASE_FORM_ID_alter
 */
  function cbib_oc_hooks_form_node_form_alter(&$form, $form_state) {

  // if you are targeting a specific content type then
  // you can access the type:
  $type = $form['#node']->type;

 // Alter the posts form to allow titles in quick reply.

  if ($type == 'document') {
    unset($form['field_formidling_og_pr']);
  }

}

/**
 * Implements hook_user_insert
 */
function cbib_oc_hooks_user_insert(&$edit, $account, $category) {
  $nid = $edit['field_f_lg_centralbibliotek']['und'];
  foreach ($nid as $id) {
    commons_follow_node_follow_node($id['target_id'], 'centralbibliotek', $account->uid);
  }
}
function cbib_oc_hooks_user_presave(&$edit, $account, $category)
{
   /*
   * Asign user a cbib based on his library location
   */
  if(isset($edit['field_library']['und'][0]['target_id']))
  {
      $library = node_load($edit['field_library']['und'][0]['target_id']);
      $cbib_ref_id = isset($library->field_centralbibliotek_ref['und'][0]['target_id']) ? $library->field_centralbibliotek_ref['und'][0]['target_id'] : null;
      if($cbib_ref_id != null)
      {
        $edit['field_centralbibliotek_ref']['und'][0]['target_id'] = $cbib_ref_id;
      }
  }
}
function cbib_oc_hooks_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
    hide($form['field_centralbibliotek_ref']);
}
/*
 * Alter the posts form to allow titles in quick reply.
 */
function cbib_oc_hooks_form_commons_bw_partial_node_form_alter(&$form, &$form_state) {
    /*
     * Overwrite the commons settings for posts.
     * Allow title field to be trigger.
     */
    if (empty($form['#entity']) || $form['#entity']->type != 'post') {
        return;
    }
    drupal_add_css(drupal_get_path('module', 'cbib_oc_hooks') . "/css/commons_posts_overwrites.css");

    // Set fields as hideable so the forms can be compacted.
    $form['title_field']['#attributes']['class'][] = 'trigger-field';
    foreach (array('body','field_media', 'field_image', 'og_group_ref', 'choice_wrapper', 'actions') as $field) {
      if (isset($form[$field])) {
        $form[$field]['#attributes']['class'][] = 'hideable-field';
      }
    }
}
/*
 * Function to keeps users on the page from which they click login.
 */
function cbib_oc_hooks_user_login_submit_handler($form, &$form_state) {
  if(isset($_SESSION['ref'])) {
      $current = $_SESSION['ref'];
      unset($_SESSION['ref']);
      drupal_goto(urldecode($current));
  }


}
/*
 * Function that allow us to prevent sending emails
 * when performing tests on the system.
 * can be controlled from the configuration form.
 */
function cbib_oc_hooks_mail_alter(&$message)
{
  // We don't want to send emails if the variable has not been set, or if it has been set and is TRUE.
  // We can use variable_get() to get the $conf variable set in our settings.php file
  // Note that by setting the default to TRUE, the default setting for the system is to be
  // a development environment. Set this to FALSE to have the default be a live environment.
    if(variable_get('oc_hooks_prevent_email_dispatch', TRUE) &&  ($message['to'] != "tfpet@odense.dk" && $message['to'] != 'tobsf@hotmail.com'))
    {
      // First: Prevent the mail from being sent
      $message['send'] = FALSE;

      // Next: Log the mail so it can be debugged if necessary
      watchdog('Development Env', 'The following email was not sent: !message', array('!message' => '<pre>' . print_r($message, TRUE) . '</pre>'));
    }
    if($message['id'] == "mimemail_rules_rules_action_mail_rules_notify_attendee_by_mail_4")
    {
        /*
         * We take over this email , and make it a event invite instead.
         * Investigate how todo with drupal mail.
         */
        $message['send'] = FALSE;
        $node = menu_get_object();
        if($node == null)
        {
            //get the node id from url , when submitting from group event
            //administration page.
            $nid = arg(1);
            // Load the node if you need to
            $node = node_load($nid);
        }
        $user = user_load($node->uid);
        $from_address = $user->mail;
        $from_mail = $user->mail;
        $to_address = $message['to'];
        $Organizer_name = $user->field_name_first['und'][0]['value'] . " " . $user->field_name_last['und'][0]['value'];
        $subject = $node->title;
        $location = "";
        $startTime = $node->field_date['und'][0]['value'];
        $endtime = $node->field_date['und'][0]['value2'];
        $domain = "centralbibliotek.dk";
        $description = $message['body'];
        $location = "";
        //Create unique identifier
        $cal_uid = date('Ymd').'T'.date('His')."-".rand()."@centralbibliotek.dk";
        if($node->field_location['und'][0] != "online")
        {
            if(!empty($node->field_address[und][0]["organisation_name"]))
            {
                $location = $node->field_address[und][0]["organisation_name"];
            }
            else
            {
                $location = $node->field_address[und][0]["thoroughfare"] . " - ".$node->field_address[und][0]["postal_code"]." ".$node->field_address[und][0]["locality"];
            }
            
        }
/*
 * The indention of this string is importent!
 * adding spaces will make it not work!
 */
$ical = "BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 16.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:STANDARD
DTSTART:16011028T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010325T093835
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:".date("Ymd\THis")."
DESCRIPTION:".$description[0]."
DTEND;TZID=Europe/Berlin:".date("Ymd\THis", strtotime($endtime))."
DTSTAMP:".date("Ymd\THis",strtotime("now"))."
DTSTART;TZID=Europe/Berlin:".date("Ymd\THis", strtotime($startTime))."
LAST-MODIFIED:".date("Ymd\THis",strtotime("now"))."
ORGANIZER;CN=\"Centralbibliotek.dk\":mailto:no-reply@centralbibliotek.dk
LOCATION:\"".$location."\"
PRIORITY:5
SEQUENCE:1
SUMMARY;LANGUAGE=da:".$subject."
TRANSP:OPAQUE
UID:".$cal_uid."
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MS-OLK-AUTOFILLLOCATION:TRUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:".$subject."
TRIGGER:-P1D
END:VALARM
END:VEVENT
END:VCALENDAR";

    //Create Email Headers
    $mime_boundary = "meeting booking";
    $headers  = "MIME-Version: 1.0\n";
    $headers .= "Content-Type: multipart/alternative;charset=UTF-8;boundary=\"$mime_boundary\"\n";
    //$headers .= "Content-class: urn:content-classes:calendarmessage\n";
    $headers .= "From: \"Centralbibliotek.dk\" <no-reply@centralbibliotek.dk>\r\n";
    
    //Create Email Body (HTML)
    $msg = "--$mime_boundary\r\n";
    $msg .= "Content-Type: text/html; charset=\"UTF-8\"\n\n";
    $msg .= theme("mimemail_message",array("body" => $description[0]));
    $msg .= "--$mime_boundary\r\n";
    $msg .= 'Content-Type: text/calendar;name="meeting.ics";method=REQUEST'."\n";
    $msg .= "Content-Transfer-Encoding: 8bit\r\n\r\n";
    $msg .= $ical;
    mail($message['to'], $subject, $msg, $headers);
    $msg .= "\n--" .$mime_boundary . "--\r\n";
    }
    
}
/*
 * Custom callback function to create a live text summary.
 */
function cbib_oc_hooks_js_create_summary()
{
    echo text_summary($_GET['text'],null,300);
    drupal_exit();
}
/**
 * Implements hook_wysiwyg_plugin().
 *
 * @see hook_wysiwyg_plugin()
 */
function cbib_oc_hooks_ckeditor_plugin() {
  return array(
    'confighelper' => array(
      // Name of the plugin used to write it.
      'name' => 'confighelper',
      // Description of the plugin - it would be displayed in the plugins management section of profile settings.
      'desc' => t('Simplify the task of changing some behaviors of CKEditor'),
      // The full path to the CKEditor plugins directory, with the trailing slash.
      'path' => drupal_get_path('module', 'cbib_oc_hooks') . '/js/ckeditor/confighelper/'
    )
  );
}
/*
 * Overwriting user/autocomplete for commons autocompletion
 */
function cbib_oc_hooks_user_autocomplete($string = '') {
  $matches = array();
  if ($string) {
    $or = db_or();
    $or->condition('mail', db_like($string) . '%', 'LIKE');
    $or->condition('name', db_like($string) . '%', 'LIKE');
    $result = db_select('users')->fields('users', array('name','mail'))->condition($or)->range(0, 10)->execute();

    foreach ($result as $user) {
      $matches[$user->name] = check_plain($user->name) . " (" . check_plain($user->mail) . ")";
    }
  }
  drupal_json_output($matches);
}
/*
 * Modify OG group admin menu to allow resend of notifcations.
 */
function cbib_oc_hooks_og_ui_get_group_admin($group_type, $gid) {
    $items = array();
    if (og_user_access($group_type, $gid, 'manage members')) {
    $items['resend_notifcation'] = array(
      'title' => t('Resend notification'),
      'description' => t('Resends original creation notifcation ( this will notify all users on the site!!)'),
      'href' => "admin/oc/resend",
    );
  }

  return $items;
}
/*
 * Callback that handles triggering the resend of the notification for
 * node creation.
 */
function cbib_oc_hooks_og_resend_notifcation($entity_type,$node_id)
{
    $node = node_load($node_id);
    commons_notify_send_message_on_shutdown($node);
    drupal_set_message(t("Notification er blevet gensendt."));
    drupal_goto(url('node/'. $node->nid));
}
/*
 * Handle resending of news node notifications
 */
function cbib_oc_hooks_node_update($node)
{
    if($node->gensend_notifcation)
    {
       drupal_set_message(t("Notification er blevet gensendt."));
       drupal_register_shutdown_function('commons_notify_send_message_on_shutdown', $node);
    }
}
/*
 * View hooks
 */
function cbib_oc_hooks_views_pre_render(&$view)
{
    if($view->name == "centralbibliotek_license" && $view->current_display == "panel_pane_6")
    {
        $content = array();
        $target_group = node_load(127);
        $links = null;
        if(!user_is_logged_in())
        {
          $links = flag_anon_link('node', $target_group,'page_manager');  
        }
        else
        {
            $links = flag_link('node', $target_group,'page_manager');
        }
        
        $follow_all_link = get_follow_all_license_link();
        $header_options = array(
        'label' => t('Header text'), // Administrative label. Not really needed here.
        //'content' => $links['flag-commons_follow_group']['title'], // Content of header text.
            'content' => (isset($links['flag-commons_follow_node']['title']) ? $links['flag-commons_follow_node']['title'] : $links['flag-anon-commons_follow_node']['title']) . $follow_all_link, // Fix for live site.
        'format' => 'full_html', // Format of header text.
        'empty' => 1, // Show even when there are no results. Set to zero otherwise.
      );
      $view->add_item('default', 'header', 'views', 'area', $header_options);
    }
    if($view->name == "search_api_arrangementer")
    {
         if(isset($_GET['filter_free_seats']))
         {
             foreach($view->result as $index => $data)
             {
                 $node = node_load($data->nid);
                 $attending = commons_events_get_raw_attendee_count($node);
                 if($node->field_number_of_attendees[LANGUAGE_NONE][0]['value'] <= $attending)
                 {
                     /*
                      * There is full attendance..remove from result set...
                      */
                     unset($view->result[$index]);
                 }
             }
         }
    }

}
/**
 * Implements theme_preprocess_pager_link().
 * needed to make filter_free_seats checkbox work with pagination.

function cbib_oc_hooks_preprocess_pager_link(&$variables) {
  if (isset($variables['parameters'])) {
    foreach ($variables['parameters'] as $key => $value) {
      // Remove all empty/false parameters from url.
      if (empty($value)) {
        unset($variables['parameters'][$key]);
      }
    }
  }
}*/
function cbib_oc_hooks_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  
    if ($form['#id'] == 'views-exposed-form-search-api-nodes-default') { // Or: if ($form['#action'] === '/foo')
      $form['#action'] = '/search';
      if (isset($form['search_api_views_fulltext'])) {
         $form['search_api_views_fulltext']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
      }
         $form['reset'] = array(
         '#markup' => '<a href="/search"><i value='.t('reset').' id="resets" class="fa fa-times"></i></a>',
         '#weight' => 1000,
         );
    }

    if($form_state['view']->name == "search_api_group")
    {
        if (isset($form['search_api_views_fulltext'])) {
         $form['search_api_views_fulltext']['#attributes']['class'][] = 'ctools-auto-submit-exclude';

         $form['reset'] = array(
         '#markup' => '<a href="/grupper"><i value='.t('reset').' id="reset" class="fa fa-times"></i></a>',
         '#weight' => 1000,
         );
      }
    }   
    if($form_state['view']->name == "search_api_arrangementer")
    {
        if (isset($form['search_api_views_fulltext'])) {
         $form['search_api_views_fulltext']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
         $path_parts = explode('/', request_uri());
         if($path_parts[3] == 'events') {
           $path = '/';
           $form['sort_order']['#default_value'] = 'DESC';
         }else {
           $path = '/arrangementer';
         }
         $form['reset'] = array(
         '#markup' => '<a href=' . $path .'><i value='.t('reset').' id="reset" class="fa fa-times"></i></a>',
         '#weight' => 1000,
         );
         /* change exposed filter
         $field_date_value = $form_state['input']['field_date_value'];
         if ($field_date_value == 'past' || $field_date_value == 'past_year' || $field_date_value == 'past_3_month') {
           $form['sort_order']['#default_value'] = 'DESC';
         }
          * 
          */
        }
        

        # the drupal checkboxes form field definition
        // Add new form item.
        /*$form['filter_free_seats'] = array(
          '#type' => 'checkbox',
          '#title' => t('Kun frie pladser'),
          '#default_value' => 0
        );

        // Create widget from new form item and place it as a second element.
        $new_form_info = array(
          'filter-free-seats' => array('value' => 'filter_free_seats'),
        );
        $form['#info'] = array_merge($new_form_info, array_diff_assoc($form['#info'], $new_form_info));*/

    }
}

 function cbib_oc_hooks_search_api_sorts_default_sort_alter(&$default_sort, array $search_sorts, $keys) {
  // Example which alters the default sort to use title instead. This is
  // example does not make a difference between default and a search page with
  // search queries provided.
      $path_parts = explode('?', request_uri());
      /* @var $path_parts type */
      if (strpos($path_parts[1], 'field_date_value=past') !== false ) {
        $default_sort->default_order = 'desc';
      }else {
        $default_sort = $search_sort;
        unset($default_sort);
      }
}

function cbib_oc_hooks_views_query_alter(&$view, &$query) {

  //simple example: change the order of the master display
  //if you want to do it only  on a certain display add something
  // like  "&&$view->current_display == 'panel_page_1'"
  if ($view->name == "search_api_arrangementer") {

    if(isset($_GET['field_address_locality']) && strtolower($_GET['field_address_locality']) != "all")
    {
        $query->add_table('field_data_field_address');
        $c = db_or()->condition('field_data_field_address.field_address_locality', $_GET['field_address_locality'], '=');
        $query->add_where(1,$c);
    }
  }
}
/*
 * Fetch uniqe event locations
 */
function cbib_oc_hooks_get_all_event_locations()
{
    $result = db_query("SELECT distinct(field_address_locality) FROM centralbibliotek.field_data_field_address WHERE  field_data_field_address.entity_id in (SELECT entity_id FROM centralbibliotek.field_data_field_date where field_data_field_date.field_date_value >= curdate())
                        AND field_data_field_address.entity_id in (SELECT nid FROM centralbibliotek.node where status = 1) order by SUBSTRING(field_address_locality, 1, 1);");
    return $result->fetchAllKeyed(0,0);
}
/**
 * Remove tabs on article content type
 */
function cbib_oc_hooks_preprocess_page(&$variables, $hook)
{

    $to_be_removed = array('node/%/clone/%');
    $path = drupal_get_path_alias();
    $path_parts = explode('/', $path);

    foreach ($variables['tabs'] as $group_key =>$tab_group)
        {
            if (is_array($tab_group))
            {
                foreach ($tab_group as $key =>$tab)
                {
                    if (isset($tab['#link']['path']) && in_array($tab['#link']['path'], $to_be_removed))
                    {
                       if ($path_parts[0] == 'node' && $path_parts[2] == 'edit') {
                          unset($variables['tabs'][$group_key][$key]);
                       }
                    }
                }
            }
        }
 }
 /*
  * Alter messages used for notifcations
 */
 function cbib_oc_hooks_commons_notify_message_selection_alter(&$message_type, $hook, &$node)
 {
     if($node->type == 'group')
     {
         //$message_type = "commons_notify_node_created";
         $message_type = "oc_commons_notify_group_created";
     }
     elseif($node->type == 'post')
     {
         //$message_type = "commons_notify_comment_created";
         $message_type =  "oc_notify_post_created";
     }
     elseif($node->type == 'event')
     { 
        //$message_type = "commons_events_event_node_created";
         $message_type =  "oc_notify_event_created";
     }
     elseif($node->type == 'license')
     {
         $message_type = "oc_notify_license_created";
     }
     elseif($node->type == 'licenses')
     {
         $message_type = "oc_notify_licenses_created";
     }
     elseif($node->type == 'news')
     {
         //$message_type = "commons_notify_node_created_no_groups";
         $message_type = "oc_commons_news_created_message";
     }
     elseif($node->type == 'page')
     {
         $message_type = "oc_notify_page_created";
     }
     elseif($node->type == 'document')
     {
         $message_type = "oc_notify_document_created";
     }
     elseif($node->type == 'centralbibliotek')
     {
         //$message_type = "commons_notify_node_created";
     }
     elseif($node->type == 'library')
     {
         $message_type = "oc_notify_library_created";
     }
 }

 function cbib_oc_hooks_node_insert($node)
 {
     /*
      * Update group node with comment date.
      */
     if($node->type == "post" || $node->type == "document" )
     {
         //Get node parent group and insert a new last post date.
         $group_node = node_load($node->og_group_ref['und'][0]['target_id']);
         if($group_node != FALSE )
         {
            $wrapper = entity_metadata_wrapper('node',$group_node);
            if(isset($wrapper->field_last_comment_date))
            {
               $wrapper->field_last_comment_date->set($node->created);
               $wrapper->save();
            }
         }
     }
 }
 function update_all_groups_with_comments()
 {
     $query = new EntityFieldQuery();
     $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'group')
      ->propertyCondition('status', NODE_PUBLISHED);

     $result = $query->execute();
     if (isset($result['node'])) {
       $news_items_nids = array_keys($result['node']);
       $news_items = entity_load('node', $news_items_nids);
       foreach($news_items as $index => $node)
       {
           $wrapper = entity_metadata_wrapper('node',$node);
            $last_post_date = get_newst_post_date($node->nid);
            if(isset($wrapper->field_last_comment_date))
            {
               $wrapper->field_last_comment_date->set($last_post_date != false ? $last_post_date : 0);
               $wrapper->save();
            }
       }
     }
 }
 function get_newst_post_date($nid)
  {
     $result = db_query("SELECT created FROM og_membership where gid='{$nid}' and entity_type = 'node' AND og_membership.etid in (SELECT nid FROM centralbibliotek.node where node.status = 1 and node.type ='post') order by created desc limit 1;");
     return $result->fetchField();
  }	
/*
 * Token hack to make urls with utf8 working.
 * Some munincipalities have disable the setting: send urls as utf8 i explorer.
 * This requires links containing special chars to be url encoded.
 */
function cbib_oc_hooks_tokens($type, $tokens, array $data = array(), array $options = array()) {
    $replacements = array();
    if($type == 'list<node>')
    {
         foreach ($tokens as $name => $original) {
             switch($name)
             {
                 case (strpos($name, ':url:encode') !== false):
                     $url_options = array('absolute' => TRUE);
                     $node = reset($data['list<node>']);
                     if($node != null)
                     {
                         $link = url('node/'. $node->nid, $url_options);
                         $link = explode('://',$link);
                         $link = rawurlencode($link[1]);
                         $replacements[$original] = $link;
                     }
                     break;
             }
         }
    }

    return $replacements;
}
/*
   * Allow users to follow all the licenses that the users cb/library subscribes too.
   * 
   */
  function user_follow_all_library_licenes()
  {
      global $user; //get the curent user
      $user_data = user_load($user->uid);
      $user_library_id = $user_data->field_library['und'][0]['target_id']; //get the current user library
      /*
       * Query all licenes that the library is subsribed too
       */
      $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'license')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->fieldCondition('field_library_ref', 'target_id', $user_library_id , '=')
        // Run the query as user 1.
        ->addMetaData('account', user_load(1));
        $result = $query->execute();
      /*
       * Subscribe the user to these if not already subscribed.
       */
      if (isset($result['node'])) {
        $license_nids = array_keys($result['node']);
        foreach($license_nids as $lid)
        {
            commons_follow_node_follow_node($lid, 'license', $user->uid);
        }
      }
      /*
       * Show pretty success message.
       */
      drupal_set_message(t("Du følger nu alle licenser som dit bibliotek har adgang til."));
      $referer = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
      drupal_goto($referer);
  }
  function get_follow_all_license_link()
  {
      if(user_is_logged_in())
      {
          return "<div style='display: inline-block;'><a title='Som dit bibliotek abonere på.' href='/flag/flag/follow/all/library' class='action-item-small'>Følg alle licenser som dit bibliotek abonnerer på</a></div>";
      }
      else
      {
          return '';
      }
      
  }
  /*
   * 
   */
function cbib_oc_hooks_flag_access($flag, $entity_id, $action, $account)
{
    //$entity = node_load($entity_id);
    $entity = menu_get_object(); // we only want to check on the main node object.
    if(isset($entity) && $entity->type == "group")
    {
        if($entity->field_og_subscribe_settings['und'][0]['value'] == 'approval' && $entity->field_og_access_default_value['und'][0]['value'] == 1)
        {
            if(!og_is_member('node',$entity->nid , 'user',$account))
            {
                drupal_add_css('.flag-wrapper {display:none;}', 'inline');
            }
        }
    }
}
/*
 * There is a problem with some groups loosing their approval required
 * setting for users.
 */
function cbib_oc_hooks_og_user_access_alter(&$perm, $context) {
  $account = $context['account'];
  $group_type = $context['group_type'];
  $group = $context['group'];
  if($group_type == "node" && $group->type == "group")
  {
      if(isset($group->field_og_subscribe_settings['und'][0]['value']) && $group->field_og_subscribe_settings['und'][0]['value'] == "approval")
      {
         if(!in_array('administrator', $account->roles) && !in_array('content moderator', $account->roles))
         {
            if(isset($perm['subscribe without approval']))
            {
                unset($perm['subscribe without approval']);
                $perm['subscribe'] = true;
            }
         }
      }
  }
}
